### PR TITLE
Instagram Searching!

### PR DESCRIPTION
**Pull request by amirahaile**

### CODE REVIEW

**Comment by amirahaile** [comment]
This looks bad…

**Comment by blip-lorist** [comment]
@amirahaile, what looks bad? 

I looked through your last few commits, checked out the branch on my computer, and it looks good. We forgot to exchange the Instagram Secret Sauce before the weekend, so I didn't have the valid client info. So we'll definitely need to get everyone that info later.

**Comment by blip-lorist** [comment]
@amirahaile WHOOPS. Looks like the base of this PR was set to the master, instead of V-8/master. I should've noticed that while merging - that would also explain why it's got like 130 commits listed here. Trying to fix this atm.

**Comment by amirahaile** [comment]
Whew. Thanks for figuring that out @lorainekv. End of the day PR need extra attention 😖Glad to see you got it all straightened out. 🎉

**Comment by blip-lorist** [comment]
@amirahaile I think it's resolved. I just pulled the V-8 master and it looks like we've got everything.

**Comment by amirahaile** [comment]
you iz amazin 💪

**Pull request merged**
